language: ruby
sudo: false
cache:
  - bundler
  - directories:
    - $HOME/.npm
script: ./script/cibuild
before_install:
  - "npm install jshint -g"
env:
  - JQUERY_VERSION: 1.8.0
  - JQUERY_VERSION: 1.8.1
  - JQUERY_VERSION: 1.8.2
  - JQUERY_VERSION: 1.8.3
  - JQUERY_VERSION: 1.9.0
  - JQUERY_VERSION: 1.9.1
  - JQUERY_VERSION: 1.10.0
  - JQUERY_VERSION: 1.10.1
  - JQUERY_VERSION: 1.10.2
  - JQUERY_VERSION: 1.11.0
  - JQUERY_VERSION: 1.11.1
  - JQUERY_VERSION: 1.11.2
  - JQUERY_VERSION: 1.12.0
  - JQUERY_VERSION: 2.0.0
  - JQUERY_VERSION: 2.1.0
  - JQUERY_VERSION: 2.1.1
  - JQUERY_VERSION: 2.1.2
  - JQUERY_VERSION: 2.1.3
  - JQUERY_VERSION: 2.2.0
