language: ruby
script: ./script/cibuild
env:
  - JQUERY_VERSION: 1.8.0
  - JQUERY_VERSION: 1.8.1
  - JQUERY_VERSION: 1.8.2
  - JQUERY_VERSION: 1.8.3
  - JQUERY_VERSION: 1.9.0
  - JQUERY_VERSION: 1.9.1
  - JQUERY_VERSION: 1.10.0
  - JQUERY_VERSION: 1.10.1
  - JQUERY_VERSION: 1.10.2
  - JQUERY_VERSION: 1.11.0
  - JQUERY_VERSION: 2.0.0
  - JQUERY_VERSION: 2.1.0
